### ISSUE TITLE
分辨率适配

### ISSUE THREAD

**Issue by xiaofeiTM233** [ba-archive/ShirokoAdventure#1]

**Comment by mark9804** [comment]
详细说明一下

**Comment by diyigemt** [comment]
我想把你绑进来可以吗

**Comment by xiaofeiTM233** [comment]
溢出屏幕
![image](https://github.com/ba-archive/ShirokoAdventure/assets/55832499/5b0ef0e1-8506-4a02-8114-59d6e86c8383)
就算不往下滑也溢出屏幕
![image](https://github.com/ba-archive/ShirokoAdventure/assets/55832499/cbe2960c-5bd8-4ba2-989c-96d781ad6494)
更新后仍旧溢出屏幕
![image](https://github.com/ba-archive/ShirokoAdventure/assets/55832499/3fa56445-add9-4245-adab-e0b5a8b1696d)
![image](https://github.com/ba-archive/ShirokoAdventure/assets/55832499/9f7243d5-d130-4c01-9e53-4b8d52fd6e0b)
