### ISSUE TITLE
点击未知按钮时游戏崩溃

### ISSUE THREAD

**Issue by xiaofeiTM233** [ba-archive/ShirokoAdventure#2]
![image](https://github.com/ba-archive/ShirokoAdventure/assets/55832499/d2815380-bb2f-4cdc-b4c1-04a61d809244)
![image](https://github.com/ba-archive/ShirokoAdventure/assets/55832499/7dc6f8f2-7eb0-44e9-8b11-46b200ee8104)
![image](https://github.com/ba-archive/ShirokoAdventure/assets/55832499/8f9926ac-ead3-425b-9318-3b570b616c80)
不是很懂unity，不会解决方案（

**Comment by mark9804** [comment]
e64be8d311ec01f4ccbff01821cf65f2c44bc4c1
